application: hosc
version: 1-1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: (/|/all|/view|/edit|/delete|/mine|/authors|/author|/svg|/supercompiler|/svgpreview|/eq|/tests|/tedit|/tdelete|/test)
  script: main.py